version: '3'

services:
  nginx:

    image: nginx:1.21-alpine
    build: ./docker/nginx
    volumes:
      - .:/mysite
    ports:
      - 1517:80
    depends_on:
      - web
    networks:
      - app

  db:
    image: mysql
    ports:
      - '3315:3306'
    environment:
       MYSQL_DATABASE: 'my_site_db'
       MYSQL_ROOT: 'root'
       MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    restart: always
    networks:
      - app

  web:
    build:
      dockerfile: ./docker/python/Dockerfile
      context: ./
    volumes:
      - .:/my_site

    command: "gunicorn mysite.wsgi:application --bind 0.0.0.0:8080"
    depends_on:
      - db
    links:
      - db
    ports:
      - 8080
    networks:
      - app
    restart: always
    environment:
      PYTHONUNBUFFERED: 1

networks:
  app:
    driver: bridge

volumes:
  data: